### PR TITLE
Base deployment supply boxes should not be redeployed from patrols' deployments

### PR DESCRIPTION
**Pull request by jmlane**

### CODE REVIEW

**Comment by jmlane** [comment]
I thought there was an issue for this, but maybe this was just something @DEL-J mentioned in chat at some point but never was documented. Does anyone else remember this?

**Comment by Diffusion9** [comment]
Its been known for a bit but hasn't been logged since we're redoing the base deployment a little bit.

**Comment by jmlane** [comment]
Added #43 to track that.

How do you want to proceed? I need to rework how `ASG_fnc_baseDeployBoxes` is called and works, since it will need to accept an array of argument boxes to be deployed at a given composition. Not sure yet if that will require altering the base data structures but it may very well.

**Comment by Diffusion9** [comment]
Go ahead and rework it as you need to. We can collab a little bit on requirements, if any, but I haven't gotten a start on the base deployment stuff yet due to the stupid odyssey with the zeus-deployed mortars, so I'm way behind on stuff.

**Pull request closed without merging**
